### ISSUE TITLE
Support for python 3

### ISSUE THREAD

**Issue by SanketDG** [fraser-hemp/gradify#17]
I realised that this doesn't have support for python3, and porting will be really easy in this case. A few change in print statements and functions and it should be good to go. Also, why is the indenting two spaces, when it is clearly mentioned in PEP8 to be [4 spaces](https://www.python.org/dev/peps/pep-0008/#indentation)? The code also has a few PEP8 errors, some lines being way too long.

If you want, I can submit a pull request and push commits fixing these over the week.

**Comment by mjnaderi** [comment]
The https://github.com/QueraTeam/gradify fork supports Python 3.
