### ISSUE TITLE
Not working for me locally in Chrome/Firefox or on server Chrome/Firefox

### ISSUE THREAD

**Issue by simsketch** [fraser-hemp/gradify#6]
This is the error I am getting.

TypeError: this.toImageData is not a function

I am loading jquery, and I see the protoype defined, so I'm not sure what's going on here.

Any ideas/suggestions? Thanks!

**Comment by fraser-hemp** [comment]
how are you calling gradify?

**Comment by simsketch** [comment]
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

```
    <script src="grad.js"></script>
    <script>
        var colors = Grad('image.jpg','frame');
        console.log(colors);
```

</script>

i have it up here - http://createsomethingtoday.com/gradify/

all i'm trying to do is console.log output of Grad function.

thanks!

**Comment by fraser-hemp** [comment]
two things straight away:
1) you must use the "new" keyword to initiate the new object (Prototype requires it) i.e. `var colors = new Grad(...)`
2) you must pass a html image element in (`<img src="..."/>`) which can be from the dom, or created in JS

**Comment by simsketch** [comment]
yeah, that did the trick...

`<div class="graddy-container">`
        `<img src="image.jpg" class="graddy" id="gimg" />`
`</div>`
        `<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>`
        `<script src="grad.js"></script>`
        `<script>`
            `var image = document.getElementById("gimg");`
            `var colors = new Grad(image, 'graddy', 5);`
            `console.log(colors);`
        `</script>`

thanks again! now to figure out what to do with all this JSON data! : )

You inspired me to write my first public project.

https://github.com/simsketch/blur-bg-fade-edge
