### ISSUE TITLE
ImportError: No module named PIL

### ISSUE THREAD

**Issue by lucidlemon** [fraser-hemp/gradify#7]
Using the script as suggested in the readme I get this error:

[00:47:04] Daniels-MacBook-Pro:gradify-master danielwinter$ python gradify.py --demo --spread
Password:
Traceback (most recent call last):
  File "gradify.py", line 3, in <module>
    from PIL import Image, ImageFilter
ImportError: No module named PIL

OSX 10.10, preinstalled python (and installed 3.5 afterwards aswell)

**Comment by fraser-hemp** [comment]
Sounds like you don't have PIL installed - install by running `$ pip install Pillow`

**Comment by lucidlemon** [comment]
Thanks. This fixed it.
Updated your Readme.md to be more user-friendly on this matter.
Also fixed a little type (missing the .py extension on the first demo)

**Comment by mahemoff** [comment]
For anyone else running Homebrew, this still didn't work due to library not being found.

I ran `brew doctor` which led me to run `brew link --overwrite python` and that fixed it.
